services:
  backend:
    env_file: .env
    build: 
        context: backend
    command: npm start
    network_mode: host
    depends_on:
        - db
    volumes:
        - files:/root/files
    restart: always
  frontend:
    env_file: .env
    build: 
        context: frontend
        args: 
            API_URL: $API_URL
            NODE_ENV: ${NODE_ENV:-production}
            FRONTEND_PREFIX: $FRONTEND_PREFIX
    network_mode: host
    command: npm start
    restart: always
    depends_on:
    - backend
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
    ports:
    - 8887:5432
    volumes:
      - database:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
    files: {}
    database: {}
