services:
  backend:
    env_file: .env.prod
    build: 
        context: backend
    command: npm start
    ports:
        - 3010:${BACKEND_PORT:-3001}
    depends_on:
        - db
    volumes:
        - files:/root/files
    restart: always
  frontend:
    env_file: .env.prod
    build: 
        context: frontend
        args: 
            API_URL: $API_URL
            NODE_ENV: ${NODE_ENV:-production}
    ports:
    - 3020:${NUXT_PORT:-3002}
    command: npm start
    restart: always
    depends_on:
    - backend
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: $TYPEORM_PASSWORD
      POSTGRES_USER: $TYPEORM_USERNAME
      POSTGRES_DB: $TYPEORM_DATABASE
    ports:
    - 5656:5432
    volumes:
      - database:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
volumes:
    files: {}
    database: {}