<template>
    <el-button
              icon="el-icon-delete-solid"
              size="small"
              v-bind="$attrs"
              type="danger"
              @click="$emit('click')"
            >Remover</el-button>
</template>