import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1616970608264 implements MigrationInterface {
    name = 'AutoGeneratedMigration1616970608264'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ADD "userDataToRequest" jsonb DEFAULT '{}'`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "userDataToRequest"`);
    }

}
