import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1616004671875 implements MigrationInterface {
    name = 'AutoGeneratedMigration1616004671875'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "startedAt" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "participation"."startedAt" IS NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "participation"."startedAt" IS NULL`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "startedAt" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
    }

}
