import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1616613958577 implements MigrationInterface {
    name = 'AutoGeneratedMigration1616613958577'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "response_test_case" RENAME COLUMN "result" TO "score"`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "response_test_case" RENAME COLUMN "score" TO "result"`);
    }

}
