import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1616018861765 implements MigrationInterface {
    name = 'AutoGeneratedMigration1616018861765'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
        await queryRunner.query(`ALTER TABLE "mechanic" DROP CONSTRAINT "FK_0fc0ccb29ff619a262dde7ad58a"`);
        await queryRunner.query(`ALTER TABLE "mechanic" ALTER COLUMN "researchGroupId" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "mechanic"."researchGroupId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mechanic" ADD CONSTRAINT "FK_0fc0ccb29ff619a262dde7ad58a" FOREIGN KEY ("researchGroupId") REFERENCES "research_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mechanic" DROP CONSTRAINT "FK_0fc0ccb29ff619a262dde7ad58a"`);
        await queryRunner.query(`COMMENT ON COLUMN "mechanic"."researchGroupId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "mechanic" ALTER COLUMN "researchGroupId" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "mechanic" ADD CONSTRAINT "FK_0fc0ccb29ff619a262dde7ad58a" FOREIGN KEY ("researchGroupId") REFERENCES "research_group"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
    }

}
