import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1616334658661 implements MigrationInterface {
    name = 'AutoGeneratedMigration1616334658661'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "mechanic" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "mechanic" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "test" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "test" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "test_application" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "test_application" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participation" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "participation" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_response" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_response" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "item_response" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "item_response" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "test_application" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "test_application" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "item" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "item" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "mechanic" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "mechanic" DROP COLUMN "createdAt"`);
    }

}
