import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1617712843434 implements MigrationInterface {
    name = 'AutoGeneratedMigration1617712843434'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "participation"."observations" IS NULL`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" DROP DEFAULT`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" SET DEFAULT ''`);
        await queryRunner.query(`COMMENT ON COLUMN "participation"."observations" IS NULL`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" SET NOT NULL`);
    }

}
