import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1617229547505 implements MigrationInterface {
    name = 'AutoGeneratedMigration1617229547505'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "response_test_case"."expectedScore" IS NULL`);
        await queryRunner.query(`ALTER TABLE "response_test_case" ALTER COLUMN "expectedScore" SET DEFAULT '0'`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT null`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "response_test_case" ALTER COLUMN "expectedScore" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "response_test_case"."expectedScore" IS NULL`);
    }

}
