import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1617914771976 implements MigrationInterface {
    name = 'AutoGeneratedMigration1617914771976'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "type"`);
        await queryRunner.query(`ALTER TABLE "test_item" DROP CONSTRAINT "FK_7064d12473e33fe92164d07a7ce"`);
        await queryRunner.query(`ALTER TABLE "test_item" ALTER COLUMN "testId" DROP NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "test_item"."testId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "test_item" ADD CONSTRAINT "FK_7064d12473e33fe92164d07a7ce" FOREIGN KEY ("testId") REFERENCES "test"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test_item" DROP CONSTRAINT "FK_7064d12473e33fe92164d07a7ce"`);
        await queryRunner.query(`COMMENT ON COLUMN "test_item"."testId" IS NULL`);
        await queryRunner.query(`ALTER TABLE "test_item" ALTER COLUMN "testId" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "test_item" ADD CONSTRAINT "FK_7064d12473e33fe92164d07a7ce" FOREIGN KEY ("testId") REFERENCES "test"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "test" ADD "type" character varying`);
    }

}
