import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1617671954635 implements MigrationInterface {
    name = 'AutoGeneratedMigration1617671954635'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" SET DEFAULT ''`);
        await queryRunner.query(`update "participation" set "observations" = '' where "observations" is null`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" SET NOT NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "participation"."observations" IS NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`COMMENT ON COLUMN "participation"."observations" IS NULL`);
        await queryRunner.query(`ALTER TABLE "participation" ALTER COLUMN "observations" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user" ALTER COLUMN "confirmationCode" DROP DEFAULT`);
        await queryRunner.query(`COMMENT ON COLUMN "user"."confirmationCode" IS NULL`);
    }

}
