import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1617748255347 implements MigrationInterface {
    name = 'AutoGeneratedMigration1617748255347'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ADD "lastVisitedItemWasFinished" boolean NOT NULL DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "lastVisitedItemWasFinished"`);
    }

}
