import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1618943900547 implements MigrationInterface {
    name = 'AutoGeneratedMigration1618943900547'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "test"`);
        await queryRunner.query(`ALTER TABLE "participation" ADD "test" jsonb`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "test"`);
        await queryRunner.query(`ALTER TABLE "participation" ADD "test" character varying`);
    }

}
