import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1618739329307 implements MigrationInterface {
    name = 'AutoGeneratedMigration1618739329307'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item" ADD "isTutorial" boolean NOT NULL DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item" DROP COLUMN "isTutorial"`);
    }

}
