import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1620345297118 implements MigrationInterface {
    name = 'AutoGeneratedMigration1620345297118'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_test_case" ADD "expanded" boolean DEFAULT true`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_test_case" DROP COLUMN "expanded"`);
    }

}
