import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1620652541245 implements MigrationInterface {
    name = 'AutoGeneratedMigration1620652541245'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test_application" ADD "controlApplicationId" integer`);
        await queryRunner.query(`ALTER TABLE "test_application" ADD CONSTRAINT "FK_c615a46430f429d59ef30213cc0" FOREIGN KEY ("controlApplicationId") REFERENCES "test_application"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test_application" DROP CONSTRAINT "FK_c615a46430f429d59ef30213cc0"`);
        await queryRunner.query(`ALTER TABLE "test_application" DROP COLUMN "controlApplicationId"`);
    }

}
