import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1620668051790 implements MigrationInterface {
    name = 'AutoGeneratedMigration1620668051790'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ADD "usesControlGroup" boolean DEFAULT false`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "usesControlGroup"`);
    }

}
