import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1622403875104 implements MigrationInterface {
    name = 'AutoGeneratedMigration1622403875104'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_response" DROP COLUMN "source"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_response" ADD "source" character varying`);
    }

}
