import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1622404594873 implements MigrationInterface {
    name = 'AutoGeneratedMigration1622404594873'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" ADD "source" character varying`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "participation" DROP COLUMN "source"`);
    }

}
