import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624671057945 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624671057945'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" alter COLUMN "score" set default '0'`);
        await queryRunner.query(`ALTER TABLE "score" alter COLUMN "max" set default '0'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
