import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624662562081 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624662562081'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "response_test_case" ADD "position" integer NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "item_test_case" ADD "position" integer NOT NULL DEFAULT '0'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_test_case" DROP COLUMN "position"`);
        await queryRunner.query(`ALTER TABLE "response_test_case" DROP COLUMN "position"`);
    }

}
