import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624671007888 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624671007888'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" alter COLUMN "score" type numeric`);
        await queryRunner.query(`ALTER TABLE "score" alter COLUMN "max" type numeric`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
    }

}
