import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624652653821 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624652653821'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "response_test_case" DROP COLUMN "expectedScore"`);
        await queryRunner.query(`ALTER TABLE "response_test_case" ADD "expectedScore" numeric DEFAULT '0'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "response_test_case" DROP COLUMN "expectedScore"`);
        await queryRunner.query(`ALTER TABLE "response_test_case" ADD "expectedScore" integer DEFAULT '0'`);
    }

}
