import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624662161850 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624662161850'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "response_test_case" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "response_test_case" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_test_case" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "item_test_case" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "item_test_case" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "item_test_case" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "response_test_case" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "response_test_case" DROP COLUMN "createdAt"`);
    }

}
