import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1624671007888 implements MigrationInterface {
    name = 'AutoGeneratedMigration1624671007888'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" DROP COLUMN "score"`);
        await queryRunner.query(`ALTER TABLE "score" ADD "score" numeric NOT NULL`);
        await queryRunner.query(`ALTER TABLE "score" DROP COLUMN "max"`);
        await queryRunner.query(`ALTER TABLE "score" ADD "max" numeric NOT NULL`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" DROP COLUMN "max"`);
        await queryRunner.query(`ALTER TABLE "score" ADD "max" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "score" DROP COLUMN "score"`);
        await queryRunner.query(`ALTER TABLE "score" ADD "score" integer NOT NULL`);
    }

}
