import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1625568983120 implements MigrationInterface {
    name = 'AutoGeneratedMigration1625568983120'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" ADD "json" character varying NOT NULL DEFAULT '{}'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "score" DROP COLUMN "json"`);
    }

}
