import {MigrationInterface, QueryRunner} from "typeorm";

export class AutoGeneratedMigration1626361544128 implements MigrationInterface {
    name = 'AutoGeneratedMigration1626361544128'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test" ADD "momentOfQuizPresentation" character varying NOT NULL DEFAULT 'after-the-test'`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "test" DROP COLUMN "momentOfQuizPresentation"`);
    }

}
